### ISSUE TITLE
Add a COPYING file and license under the GNU GPLv3

### ISSUE THREAD

**Issue by nomad-geek** [KingLinkTiger/RPIKiosk#1]
Source is missing a license. Please add GPLv3
https://choosealicense.com/licenses/gpl-3.0/

**Comment by KingLinkTiger** [comment]
License was added with commit [c1f8ebf](https://github.com/KingLinkTiger/RPIKiosk/commit/c1f8ebf9ecb056e8c8ab4c1f19d5c0dba305ef50)
